### ISSUE TITLE
This plugin crashed.

### ISSUE THREAD

**Issue by MeylinK** [mpm11011/galaxy-integration-rpcs3#9]

**Comment by mpm11011** [comment]
Please describe the issue. Does the crash occur on clicking Connect, or after? Have you gotten the latest version of this plugin? 

Also, upload the GalaxyClient and Vision logs from `C:\ProgramData\GOG.com\Galaxy\logs` if you are on Windows.

**Comment by mjsf12** [comment]
same here
[plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log](https://github.com/mpm11011/galaxy-integration-rpcs3/files/3637952/plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log)
![Sem título](https://user-images.githubusercontent.com/1287082/65362310-4eee3480-dbdd-11e9-9495-1d75c15d61b2.png)

name of plugin is ColecoVision ? its right?
i think bug is this module
**ModuleNotFoundError: No module named 'devita.sfo'**
sorry my bad english  :/

**Comment by mpm11011** [comment]
I see the problem. When you download a zip from GitHub, it doesn't include submodules.

Download a zip of [this repo](https://github.com/mpm11011/devita) and put the contents in the "devita" folder in "rpcs3_80F9D16B-5D72-4B95-9D46-2A1EF417C1FC."

Let me know if that solves the issue, and then I can update the installation instructions.

**Comment by MeylinK** [comment]
Problem is fixed, but it doesn't seem to detect games. I set the main directory to RPCS3 folder, but it doesn't seem to detect games. Maybe because they're in another folder ?

**Comment by mjsf12** [comment]
same meylink , no show my games.

**Comment by MeylinK** [comment]
Copy your game folder to RPCS3/dev_hdd0/disc, it should work hopefully.

**Comment by mpm11011** [comment]
The plugin reads from both the 'dev_hdd0/disc/' and 'dev_hdd0/game/' directories, so there should be no need to move folders between the two. It may take some time for the games to import, so I would be patient and keep an eye on the plugin logs.

**Comment by Netwell09** [comment]
[plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log](https://github.com/mpm11011/galaxy-integration-rpcs3/files/7968119/plugin-vision-80F9D16B-5D72-4B95-9D46-2A1EF417C1FC.log)
same problem. still not working
